# Generated by Django 4.2.16 on 2025-05-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='default_address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
