# Generated by Django 5.1.3 on 2025-07-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_isbn_book_publication_date_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
