# Generated by Django 4.2.16 on 2025-08-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_book_show_on_homepage_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
